version: '3.3'
services:
    thingsix-forwarder:
        ports:
          - 'xxx.xx.xx.xxx:1680:1680/udp'   # <----- CHANGE TO YOUR DESIRED IP
        expose:
          - '8888'
        restart: unless-stopped
        volumes:
          - '/opt/thingsix-forwarder:/etc/thingsix-forwarder:Z'   # <----- :Z is needed for SELinux, you might want to remove that
        container_name: thingsix-forwarder
        image: 'ghcr.io/thingsixfoundation/packet-handling/forwarder'
        environment:
          - default_frequency_plan=EU868
        labels:
          - com.centurylinklabs.watchtower.enable=true
        networks:
          - monitoring

    watchtower:
        container_name: watchtower
        volumes:
          - '/var/run/docker.sock:/var/run/docker.sock'
        image: containrrr/watchtower
        privileged: true
        environment:
          - WATCHTOWER_LABEL_ENABLE=true
          - WATCHTOWER_POLL_INTERVAL=3200

    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      restart: unless-stopped
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z   # <----- :Z is needed for SELinux, you might want to remove that
        - prometheus_data:/prometheus:Z   # <----- :Z is needed for SELinux, you might want to remove that
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--web.enable-lifecycle'
      expose:
        - 9090
      networks:
        - monitoring


volumes:
  prometheus_data: {}

networks:
  monitoring:
    driver: bridge
